apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      existingSecret: mysql-auth
    primary:
      persistence:
        enabled: false 
