apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    auth:
      rootPassword: my-root-pass       # root password
      username: myuser                 # new user
      password: mypass123              # password for new user
      database: mydb                   # database created for that user
    primary:
      persistence:
        enabled: false 
