apiVersion: ENC[AES256_GCM,data:x+s=,iv:e9Q+O4zkxIJ6Y+VESspMNiNB0uxW7x/nn8VHglzsxq0=,tag:tI5EN1Tp7Wfjz2sjsNThgw==,type:str]
kind: ENC[AES256_GCM,data:56xcWtFS,iv:ToU/9Qsutp4JNenDSMKypQNnM/tV+mUlLrJpgLmOy/0=,tag:JDGvG7gwEX7DF4V+2IzHCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d8MeFv9t0kVAvQ==,iv:nR0yffzHqghV2dnAppk3cZGxEbloXNgIA5Xr1nsAMzA=,tag:OI3ofR1ypj/08korUWAr5w==,type:str]
    namespace: ENC[AES256_GCM,data:0fgkebnCqw==,iv:U+2KoXu3xxf91H3Rm3Q2++FeD9J/v8FzCeN2S7vUmto=,tag:pwgwi/1QVzIXI61jdwjd0Q==,type:str]
type: ENC[AES256_GCM,data:zOfZ1Utd,iv:lTn8Y03QqUaGBnCAHHCYAJkj4MVmClXdWOloZ+Pt70I=,tag:6esfPY5UKbcN9KGmithgYA==,type:str]
stringData:
    mysql-root-password: ENC[AES256_GCM,data:8KVYW6WV4pSXVT2VkFI=,iv:Gjc6sZv4mDPrz1+5hhLtcnjFxXPo/7E+1DwI2D9BLTM=,tag:o2xGBsWPDCFiy2V+rzM7xw==,type:str]
    mysql-password: ENC[AES256_GCM,data:dH4obT9vrioIWNwxAb4=,iv:9rTqOCdQagDNfIKRBblbhx9XbD7qw5EnLoPFmr/t7ng=,tag:H4oaruRL7ggt48kYj468Yw==,type:str]
sops:
    age:
        - recipient: age1j6mzq2a3hjg2cf9tjmrxjx3s4fyds2e9zzgpmsu98pd8x8ndj4fscvfepy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WTFQN2w0aCtDc1BBNncy
            S3VqeXhPci9kSkkxVFVSZkw5TXRJaVA1Z2pVCnhURnY3UUNwWjkyN09OVjBOU3FM
            MWs4VXN6SUdZMTE2SWtwcE8wY2kyeGsKLS0tIE9rN2pzaTlnYmlpVXk0YWE4QmJQ
            aTZZTHAzNTM0SC9mSUVHQkR1aUw2NWMK/wQP/B22NzHuHXEPlQza1qDntRgmQo38
            JX5VDck5j9TmritmDiY3ZhojqWAStKNPCFVxVzUO/bXqD77L5JiVhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T06:51:04Z"
    mac: ENC[AES256_GCM,data:bWzVbbsNcFZ3LI95O67fO4xtzweziEkkP9eEd6Qb2e4NwMIV+6xil3FmXnKAGg5eihAn6JHTCRrpmtrqJClInLiNVtKamsXcIrdOwmyfe9fp3wgyI6+DEqKUs87FPGiqigG0gqvXIolpVz6gqqihVVc/LGcZfLs5Wwq6h3aBJ+I=,iv:n3+zKaFUr/hBLLa2Q6iHpWCAhCtb1MN2K8eTBPM6JZI=,tag:c3wT5LwA67z/YMjxnsiDTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
