apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: "13.2.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  values:
    service:
      type: NodePort
